--- #YAML:1.0
name: CGI-Application-ValidateRM
version: 1.11
license: perl
distribution_type: module
requires:
  CGI::Application: 3
  Data::FormValidator: 3
  HTML::FillInForm: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  CGI::Application::ValidateRM:
    file: lib/CGI/Application/ValidateRM.pm
    version: 1.11
generated_by: Module::Build version 0.21
